version: "3.5"

services: 
    server:
        image: rabbitmq:management
        ports: 
            - "15672:15672"
            - "5672:5672"
        restart: always
        container_name: "rabbitmq"
        environment: 
            - RABBITMQ_NODENAME=rabbit@rabbitmq
        volumes: 
            - ./data:/var/lib/rabbitmq